CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "PUBLIC"."FLIGHT"(
    "ID" INTEGER NOT NULL AUTO_INCREMENT,
    "FLIGHT_NUMBER" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."FLIGHT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.FLIGHT;
CREATE MEMORY TABLE "PUBLIC"."GATE"(
    "ID" INTEGER NOT NULL AUTO_INCREMENT,
    "GATE_NUMBER" VARCHAR(255) NOT NULL,
    "FLIGHT_ID" INTEGER,
    "VERSION" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."GATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.GATE;
ALTER TABLE "PUBLIC"."GATE" ADD CONSTRAINT "PUBLIC"."UK_EOND20VK24ML0GWK3RS7U6T79" UNIQUE("GATE_NUMBER");
ALTER TABLE "PUBLIC"."FLIGHT" ADD CONSTRAINT "PUBLIC"."UK_AUCISQX7ARN3FI6EYJMSVQDB3" UNIQUE("FLIGHT_NUMBER");
ALTER TABLE "PUBLIC"."GATE" ADD CONSTRAINT "PUBLIC"."FK5ERUECX3XBLYMMXN2GWG34759" FOREIGN KEY("FLIGHT_ID") REFERENCES "PUBLIC"."FLIGHT"("ID") NOCHECK;
